accessKeyId: testid
accessKeySecret: testsecret
ipv4_check_url: ipv4.icanhazip.com
ipv6_check_url: ipv6.icanhazip.com
ttl: 600
interval: 10
customer:
    - domain: your_domain.com
      ipv4_rr: subdomain1
      ipv6_rr: subdomain2
    - domain: another_domain.com
      ipv4_rr: subdomain1
      ipv6_rr: subdomain2