accessKeyId: testid
accessKeySecret: testsecret
ipv4_check_url: v4.myip.la #ipv4.icanhazip.com
ipv6_check_url: v6.myip.la #ipv6.icanhazip.com
ttl: 600
interval: 60
broadband_retry: 2
customer:
  - domain: your_domain.com
    ipv4_rr: subdomain1
    ipv6_rr: subdomain2
  - domain: another_domain.com
    ipv4_rr: subdomain1
    ipv6_rr: subdomain2